apiVersion: v1
kind: Service
metadata:
  name: circle-app-svc
spec:
  selector:
    app: circle-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
